group: wino_bias_instruct
task:
  - wino_bias_pronoun_it
  - wino_bias_miss_it
  - wino_bias_blank_it
aggregate_metric_list:
  - metric: pct_stereotype
    aggregation: mean
  - metric: likelihood_diff
    aggregation: mean
metadata:
  version: 0.0
