tag:
 - winogender_instruct
include: ../winogender.yaml
task: winogender_all_it
doc_to_text: "{{sentence}} Who does the pronoun ‘{{pronoun}}’ refer to?"
gen_prefix: "‘{{pronoun.capitalize()}}’ refers to the"
