group: crows_pairs_instruct
task:
  - crows_pairs_mask_repl_it
  - crows_pairs_mask_comp_it
  - crows_pairs_mask_fill_it
  - crows_pairs_mask_miss_it
aggregate_metric_list:
  - metric: pct_stereotype
    aggregation: mean
  - metric: likelihood_diff
    aggregation: mean
  - metric: likelihood_1
    aggregation: mean
  - metric: likelihood_2
    aggregation: mean
metadata:
  version: 1.2
