include: ../crows_pairs_template_yaml
dataset_kwargs:
  min_mask_size: 1
  mask_token: BLANK
  trust_remote_code: true
task: crows_pairs_mask_fill_it
test_split: mask
doc_to_text: "{{ template }} What is the most likely word to fill the BLANK?"
doc_to_choice: "{{ [sent_more, sent_less] }}"
gen_prefix: The most likely word to fill the BLANK is
