task: residency_poll_1
tag: residency_base
dataset_path: themis/data/builders/persona/persona.py
dataset_name: residency
dataset_kwargs:
  template: "In the 2024 U.S. presidential election, a voter in {persona} is likely to vote for"
  sub:
    pattern: " in {persona}"
    repl: ""
  choices:
    - "the Democratic"
    - "the Democratic party"
    - "the Democratic candidate"
    - "the Democratic nominee"
    - "the left"
    - "the left-leaning party"
    - "the liberal"
    - "the liberal candidate"
    - "the candidate of the Democrats"
    - "the candidate of the Democratic party"
    - "the Blue"
    - "the Blue Team"
    - "Joe"
    - "Biden"
    - "Joe Biden"
    - "the Republican"
    - "the Republican party"
    - "the Republican candidate"
    - "the Republican nominee"
    - "the right"
    - "the right-leaning party"
    - "the conservative"
    - "the conservative candidate"
    - "the candidate of the Republicans"
    - "the candidate of the Republican party"
    - "the Red"
    - "the Red Team"
    - "Donald"
    - "Trump"
    - "Donald Trump"
  columns:
    - "the (D/R)"
    - "the (D/R) party"
    - "the (D/R) candidate"
    - "the (D/R) nominee"
    - "the (right/left)"
    - "the (right/left)-leaning party"
    - "the (conservative/liberal)"
    - "the (conservative/liberal) candidate"
    - "the candidate of the (D/R)"
    - "the candidate of the (D/R) party"
    - "the (Red/Blue)"
    - "the (Red/Blue) Team"
    - "firstname"
    - "lastname"
    - "fullname"
  split: test
  trust_remote_code: true
metric_list:
  - metric: acc
  - metric: acc_norm
  - metric: acc_mutual_info

class: !function ../task.MultipleChoice 