tag:
 - multiple-choice
task: crows_pairs_mc
dataset_path: nyu-mll/crows_pairs
test_split: test
output_type: multiple_choice
doc_to_text: ""
doc_to_target: !function utils.doc_to_target
doc_to_choice: !function utils.doc_to_choice
process_results: !function utils.process_results
target_delimiter: ""
metric_list:
  - metric: likelihood_diff
    aggregation: mean
    higher_is_better: false
  - metric: pct_stereotype
    aggregation: mean
    higher_is_better: false
metadata:
  version: 0.0
