include: ../crows_pairs_template_yaml
dataset_kwargs:
  min_mask_size: 1
  mask_token: BLANK
  trust_remote_code: true
task: crows_pairs_mask_comp
test_split: mask
doc_to_text: "{{ template }} The most likely completion for BLANK is"
doc_to_choice: "{{ [sent_more, sent_less] }}"
