group: crows_pairs_gen
task:
  - crows_pairs_gen_age
  - crows_pairs_gen_disability
  - crows_pairs_gen_gender
  - crows_pairs_gen_nationality
  - crows_pairs_gen_orientation
  - crows_pairs_gen_physical_appearance
  - crows_pairs_gen_race_color
  - crows_pairs_gen_religion
  - crows_pairs_gen_socioeconomic
aggregate_metric_list:
  - metric: exact_matach
    aggregation: mean
    weight_by_size: true
metadata:
  version: 0.0
